-- NUXAR Perfume Database Migration SQL
-- Target: Supabase SQL Editor
-- This script will create a new 'perfumes' table and populate it with 66 items.

-- 1. DROP old table if exists (CAUTION: deletes old data)
DROP TABLE IF EXISTS perfumes;

-- 2. CREATE the new perfumes table
CREATE TABLE perfumes (
    id SERIAL PRIMARY KEY,
    name TEXT NOT NULL,
    brand TEXT NOT NULL,
    full_name TEXT NOT NULL,
    year INTEGER,
    gender TEXT CHECK (gender IN ('pria', 'wanita', 'unisex')),
    category TEXT,
    concentration TEXT,
    notes JSONB,
    karakter TEXT,
    penggunaan TEXT,
    description TEXT,
    is_official BOOLEAN DEFAULT true,
    note TEXT,
    display_order INTEGER,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. INSERT Cowok/Unisex perfumes (from perfumeDataCowok.ts)
INSERT INTO perfumes (name, brand, full_name, year, gender, category, concentration, notes, karakter, penggunaan, description, is_official, note, display_order) VALUES
('Desire Blue', 'Dunhill', 'Dunhill Desire Blue', 2004, 'pria', 'Fresh Aromatic Aquatic', 'EDT', '{"top": ["Litchi", "Mandarin Orange", "Lotus", "Bergamot"], "middle": ["Sea Notes", "Orange", "Brazilian Rosewood"], "base": ["Tonka Bean", "Amber", "Musk", "Benzoin"]}', 'Segar, bersih, maskulin elegan', 'Siang hari, kantor, aktivitas harian', 'Desire Blue adalah perwujudan sempurna dari pria modern yang hidup di antara kota dan alam bebas.', true, NULL, 1),
('212 Men', 'Carolina Herrera', 'Carolina Herrera 212 Men', 1999, 'pria', 'Woody Floral Musk', 'EDT', '{"top": ["Green Notes", "Grapefruit", "Bergamot", "Lavender"], "middle": ["Ginger", "Violet", "Gardenia", "Sage"], "base": ["Musk", "Sandalwood", "Incense", "Vetiver"]}', 'Maskulin modern, profesional, urban', 'Kantor, siang hingga sore hari, acara semi-formal', '212 Men lahir dari energi Manhattan yang dinamis.', true, NULL, 2),
('Libre', 'Yves Saint Laurent', 'YSL Libre', 2019, 'wanita', 'Floral Aromatic', 'EDP', '{"top": ["Lavender", "Mandarin Orange", "Blackcurrant", "Petitgrain"], "middle": ["Lavender", "Orange Blossom", "Jasmine"], "base": ["Madagascar Vanilla", "Musk", "Cedar", "Ambergris"]}', 'Feminin berapi-api, bebas, kontradiktif', 'Malam hari, acara spesial, daily wear modern', 'Libre adalah deklarasi kebebasan — kontradiksi yang indah antara lavender Prancis maskulin dan fleur d''oranger Maroko yang feminin.', true, 'Officially feminine, namun karakter lavender-nya menjadikannya favorit unisex.', 3),
('Vision III', 'Jaguar', 'Jaguar Vision III', 2014, 'pria', 'Aromatic Fougère', 'EDT', '{"top": ["Lemon", "Bergamot", "Lavender"], "middle": ["Cardamom", "Jasmine"], "base": ["Sandalwood", "Vanilla", "Musk"]}', 'Bersih, hangat, maskulin accessible', 'Harian, kantor ringan, casual', 'Vision III meneruskan filosofi lini Jaguar: parfum untuk pria yang mengapresiasi kesederhanaan berkelas.', true, NULL, 4),
('Black', 'Etienne Aigner', 'Etienne Aigner Black', 2001, 'pria', 'Aromatic Fougère Leathery', 'EDT', '{"top": ["Grapefruit", "Orange", "Bergamot"], "middle": ["Mint", "Oakmoss", "Pine Tree"], "base": ["Leather", "Tonka Bean", "Musk"]}', 'Maskulin kuat, tajam, profesional klasik', 'Kantor, sore-malam, acara formal', 'Aigner Black adalah representasi dari pria yang tahu nilai ketenangan.', true, NULL, 5),
('Cool Water', 'Davidoff', 'Davidoff Cool Water Men', 1988, 'pria', 'Aromatic Aquatic Fougère', 'EDT', '{"top": ["Sea Water", "Lavender", "Mint", "Green Notes", "Rosemary", "Coriander"], "middle": ["Neroli", "Jasmine", "Geranium"], "base": ["Musk", "Sandalwood", "Oakmoss", "Tobacco", "Amber"]}', 'Ikon kesegaran, aquatic pionir, timeless', 'Semua waktu, olahraga, harian, cuaca panas', 'Cool Water bukan sekadar parfum — ini adalah momen bersejarah dalam dunia wewangian.', true, NULL, 6),
('Sauvage', 'Christian Dior', 'Dior Sauvage EDT', 2015, 'pria', 'Aromatic Fougère', 'EDT', '{"top": ["Calabrian Bergamot", "Pepper"], "middle": ["Sichuan Pepper", "Lavender", "Pink Pepper", "Vetiver", "Patchouli", "Geranium"], "base": ["Ambroxan", "Cedar", "Labdanum"]}', 'Liar, bebas, maskulin dominan, modern klasik', 'Serba guna — kantor, malam, outdoor, harian', 'Dior Sauvage adalah parfum terlaris di dunia.', true, NULL, 7),
('Pramugari', 'Non-Official / Lokal', 'Parfum Pramugari (Generic Name)', NULL, 'unisex', 'Fresh Clean Musk', 'EDT / Body Mist', '{"top": ["Citrus blend", "Bergamot", "Light Aldehydes"], "middle": ["White Floral", "Clean Musk", "Soft Powder"], "base": ["White Musk", "Light Sandalwood", "Warm Amber"]}', 'Bersih profesional, fresh powdery, neat', 'Lingkungan profesional tertutup, kantor, sehari-hari', 'Sebutan ''parfum pramugari'' adalah aroma yang sangat populer karena kesegarannya yang sopan dan profesional.', false, 'Aroma segar khas profesional yang sangat disukai.', 8),
('Essential Sport', 'Lacoste', 'Lacoste Essential Sport', 2009, 'pria', 'Aromatic Citrus Woody', 'EDT', '{"top": ["Bergamot", "Grapefruit", "Ginger"], "middle": ["Nutmeg", "Juniper"], "base": ["Vetiver", "Musk", "Patchouli"]}', 'Aktif, energik, segar sporty', 'Olahraga, outdoor, aktivitas fisik, casual siang', 'Essential Sport diciptakan untuk pria yang hidupnya bergerak.', true, NULL, 9),
('Raffi Ahmad Signature', 'Non-Official / Lokal', 'Parfum Raffi Ahmad (Inspired/Clone)', NULL, 'pria', 'Woody Aromatic Chypre', 'EDP / EDT', '{"top": ["Pineapple", "Bergamot", "Black Currant", "Apple"], "middle": ["Birch", "Patchouli", "Jasmine", "Rose"], "base": ["Musk", "Oakmoss", "Ambergris", "Vanilla"]}', 'Charismatic, powerfull, luxury aspirational', 'Acara penting, malam hari, signature statement', 'Parfum dengan karakter aroma mewah yang memberikan kesan percaya diri di setiap kesempatan.', false, 'Aroma mewah dengan karakter yang sangat kuat dan berkesan.', 10),
('Black Opium', 'Yves Saint Laurent', 'YSL Black Opium EDP', 2014, 'wanita', 'Oriental Vanilla Gourmand', 'EDP', '{"top": ["Coffee", "Pink Pepper", "Orange Blossom"], "middle": ["Jasmine", "Bitter Almond"], "base": ["Vanilla", "Patchouli", "Cedar"]}', 'Sensual, adiktif, dark feminine, malam', 'Malam hari, pesta, date night, musim dingin', 'Black Opium adalah parfum yang berani membuat pernyataan.', true, NULL, 11),
('1 Million', 'Paco Rabanne', 'Paco Rabanne 1 Million EDT', 2008, 'pria', 'Oriental Spicy Leathery', 'EDT', '{"top": ["Blood Mandarin", "Grapefruit", "Mint"], "middle": ["Cinnamon", "Rose", "Spice Notes"], "base": ["Leather", "Amber", "Patchouli", "Woody Notes"]}', 'Percaya diri, glamorous, party-ready, statement', 'Malam hari, pesta, clubbing, acara glamor', '1 Million adalah definisi liquid confidence.', true, NULL, 12),
('Aventus', 'Creed', 'Creed Aventus EDP', 2010, 'pria', 'Fruity Chypre Woody Aromatic', 'EDP', '{"top": ["Pineapple", "Bergamot", "Black Currant", "Apple"], "middle": ["Birch", "Patchouli", "Jasmine", "Rose"], "base": ["Musk", "Oakmoss", "Ambergris", "Vanilla"]}', 'Power, kemewahan absolut, sukses, iconic', 'Acara penting, travel, signature scent, investasi', 'Aventus adalah puncak absolut maskulin fragrance.', true, NULL, 13),
('Baccarat Rouge 540', 'Maison Francis Kurkdjian', 'MFK Baccarat Rouge 540 EDP', 2015, 'unisex', 'Floral Woody Amber', 'EDP', '{"top": ["Saffron", "Jasmine"], "middle": ["Amberwood", "Ambergris"], "base": ["Fir Resin", "Cedar"]}', 'Ikonik, ultra-mewah, warm-metallic, unforgettable', 'Acara eksklusif, signature mewah, travel luxury', 'Baccarat Rouge 540 adalah fenomena budaya.', true, NULL, 14),
('Pour Homme Extreme', 'Bvlgari', 'Bvlgari Pour Homme Extreme', 2002, 'pria', 'Aromatic Aquatic Woody', 'EDT', '{"top": ["Tea", "Grapefruit", "Bergamot"], "middle": ["Pepper", "Cardamom"], "base": ["Musk", "Oakmoss"]}', 'Clean tea-forward, sophisticated minimalis', 'Kantor, siang hari, daily refined', 'Bvlgari Pour Homme Extreme adalah ode pada teh.', true, NULL, 15),
('Aqva Pour Homme', 'Bvlgari', 'Bvlgari Aqva Pour Homme', 2005, 'pria', 'Aquatic Aromatic Citrus', 'EDT', '{"top": ["Mandarin Orange", "Orange"], "middle": ["Seaweed", "Lavender"], "base": ["Amber", "Cedar"]}', 'Aquatic mediterania, segar bersih, summer vibes', 'Cuaca panas, pantai, summer, aktivitas outdoor', 'Aqva Pour Homme menangkap esensi Mediterania dengan cara yang sangat puitis.', true, NULL, 16),
('Our Moment', 'One Direction', 'One Direction Our Moment EDP', 2013, 'wanita', 'Floral Fruity', 'EDP', '{"top": ["Red Currant", "Pink Grapefruit"], "middle": ["Jasmine", "Freesia"], "base": ["Musk", "Patchouli"]}', 'Girly, ceria, youthful, nostalgic', 'Remaja, hangout, casual, daily feminine', 'Our Moment adalah kapsul waktu.', true, NULL, 17),
('Eros', 'Versace', 'Versace Eros EDT', 2012, 'pria', 'Oriental Woody Aromatic', 'EDT', '{"top": ["Mint", "Green Apple", "Lemon"], "middle": ["Tonka Bean", "Ambroxan", "Geranium"], "base": ["Vanilla", "Vetiver", "Oakmoss", "Cedar"]}', 'Maskulin sensual, seduktif modern, kuat namun manis', 'Malam hari, date night, acara sosial, clubbing', 'Terinspirasi dari Eros — Dewa Cinta Yunani.', true, NULL, 18),
('212 Sexy Men', 'Carolina Herrera', 'Carolina Herrera 212 Sexy Men EDT', 2007, 'pria', 'Oriental Spicy Woody', 'EDT', '{"top": ["Mandarin Orange", "Bergamot"], "middle": ["Pepper", "Cardamom"], "base": ["Vanilla", "Sandalwood", "Musk"]}', 'Sensual, maskulin hangat, sophisticated seduktif', 'Malam hari, date night, acara romantic', '212 Sexy Men adalah versi 212 yang memilih sisi gelap Manhattan.', true, NULL, 19),
('For Men', 'Mercedes-Benz', 'Mercedes-Benz For Men EDT', 2012, 'pria', 'Woody Aromatic Citrus', 'EDT', '{"top": ["Bergamot", "Lemon", "Mandarin Orange"], "middle": ["Violet"], "base": ["Vetiver", "Patchouli", "Cedar"]}', 'Maskulin modern, clean-woody, urban sophisticated', 'Harian, kantor, casual professional', 'Mercedes-Benz For Men adalah visual dari interior kulit sedan mewah yang baru dipoles.', true, NULL, 20),
('Orgasm', 'HMNS', 'HMNS Orgasm', NULL, 'unisex', 'Floral Amber Musk', 'EDP', '{"top": ["Citrus Blend", "Bergamot"], "middle": ["White Floral", "Rose", "Violet"], "base": ["Amber", "Musk", "Woody Notes"]}', 'Sensual modern, luxury-floral, tahan sangat lama', 'Daily wear premium, malam, acara spesial', 'HMNS Orgasm adalah proof bahwa parfum lokal Indonesia telah mencapai standar dunia.', true, 'Brand lokal Indonesia.', 21),
('Legend', 'Mont Blanc', 'Mont Blanc Legend EDT', 2011, 'pria', 'Aromatic Aquatic Woody', 'EDT', '{"top": ["Lavender", "Pineapple", "Bergamot"], "middle": ["Apple", "Oakmoss", "Rose"], "base": ["Tonka Bean", "Sandalwood", "Musk"]}', 'Profesional, clean modern, accessible mewah', 'Kantor, sehari-hari, acara semi-formal', 'Mont Blanc Legend adalah definisi dari ''gentleman''s daily driver''.', true, NULL, 22),
('Daisy', 'Marc Jacobs', 'Marc Jacobs Daisy EDT', 2007, 'wanita', 'Floral Woody Musk', 'EDT', '{"top": ["Strawberry", "Violet Leaves", "Grapefruit"], "middle": ["Violet Petals", "Jasmine", "Gardenia"], "base": ["Musk", "Vanilla", "White Woods"]}', 'Cheerful, innocent, spring feminine, youthful', 'Siang hari, hangout, casual feminine, musim semi', 'Daisy adalah quintessential spring fragrance.', true, 'Marc Jacobs memiliki banyak varian.', 23),
('Aigner Blue', 'Etienne Aigner', 'Etienne Aigner Blue', 2003, 'pria', 'Aromatic Citrus Fresh', 'EDT', '{"top": ["Bergamot", "Lemon"], "middle": ["Water Notes", "Lavender"], "base": ["Musk", "Sandalwood", "Amber"]}', 'Ringan, bersih, youthful segar', 'Harian casual, siang hari, santai', 'Aigner Blue adalah parfum yang tidak meminta banyak dari pemakainya.', true, NULL, 24),
('Light Blue Pour Homme', 'Dolce & Gabbana', 'D&G Light Blue Pour Homme EDT', 2007, 'pria', 'Aromatic Citrus Woody', 'EDT', '{"top": ["Sicilian Lemon", "Apple", "Bluebell"], "middle": ["Bamboo", "Jasmine", "Pepper"], "base": ["Musk", "Cedar", "Incense"]}', 'Mediterranean summer, segar bersih, casual sophisticated', 'Musim panas, santai, liburan, casual outdoor', 'Light Blue Pour Homme adalah surat cinta untuk musim panas di Sisilia.', true, NULL, 25),
('Polo Sport', 'Ralph Lauren', 'Ralph Lauren Polo Sport EDT', 1993, 'pria', 'Aromatic Aquatic Citrus', 'EDT', '{"top": ["Mint", "Lemon", "Citrus Blend"], "middle": ["Ginger", "Sea Notes", "Eucalyptus"], "base": ["Musk", "Sandalwood", "Oakmoss"]}', 'Active, fresh athletic, American classic', 'Olahraga, outdoor, casual, iklim panas', 'Polo Sport adalah parfum yang mendefinisikan era 90-an active lifestyle.', true, NULL, 26),
('My Way', 'Giorgio Armani', 'Giorgio Armani My Way EDP', 2020, 'wanita', 'Floral Musky Woody', 'EDP', '{"top": ["Orange Blossom", "Bergamot"], "middle": ["Tuberose", "Indian Jasmine", "White Cedar"], "base": ["Vanilla", "White Musk", "Virginia Cedar"]}', 'Modern feminine, sophisticated freedom, warm floral', 'Daily wear premium, kantor feminin, acara semi-formal', 'My Way adalah manifesto wanita modern yang percaya bahwa kebebasan dan keeleganan bisa hadir dalam satu nafas.', true, NULL, 27),
('Kenzo Homme', 'Kenzo', 'Kenzo Homme EDT', 1991, 'pria', 'Aromatic Aquatic Woody', 'EDT', '{"top": ["Marine Notes", "Bergamot", "Spearmint"], "middle": ["Pine", "Vetiver", "Sage"], "base": ["Sandalwood", "Musk", "Amber"]}', 'Maskulin natural, hutan-laut, earthy fresh', 'Harian, outdoor, cuaca hangat, alam terbuka', 'Kenzo Homme adalah parfum yang bercerita tentang perbatasan antara laut dan hutan.', true, NULL, 28),
('Santal 33', 'Le Labo', 'Le Labo Santal 33 EDP', 2011, 'unisex', 'Woody Aromatic Leathery', 'EDP', '{"top": ["Violet", "Cardamom", "Iris"], "middle": ["Ambroxan", "Papyrus", "Cedarwood"], "base": ["Sandalwood", "Leather", "Musk", "Cashmere Wood"]}', 'Kultus, ikonik, woody smoky, gender-fluid', 'Signature scent, daily premium, acara kreatif', 'Santal 33 adalah fenomena budaya yang melampaui dunia parfum.', true, NULL, 29),
('For Him', 'Narciso Rodriguez', 'Narciso Rodriguez For Him EDT', 2007, 'pria', 'Woody Musky Aromatic', 'EDT', '{"top": ["Violet", "Aromatic Herbs"], "middle": ["Musk", "Cardamom"], "base": ["Patchouli", "Amber", "Woody Notes"]}', 'Intim, skin scent, musk-forward, subtle powerful', 'Date night, signature personal, intimate settings', 'For Him adalah antitesis dari parfum yang berteriak.', true, NULL, 30),
('Pour Homme (Kenzo Daun)', 'Kenzo', 'Kenzo Pour Homme EDT', 1991, 'pria', 'Aromatic Green Aquatic', 'EDT', '{"top": ["Marine Notes", "Bergamot", "Spearmint"], "middle": ["Pine", "Vetiver", "Sage", "Birch"], "base": ["Sandalwood", "Musk", "Amber"]}', 'Green aquatic earthy, alami maskulin, unik', 'Outdoor, alam terbuka, daily green-lover', 'Dikenal di Indonesia dengan sebutan ''Kenzo Daun''.', true, 'Di Indonesia dikenal sebagai ''Kenzo Daun'' merujuk pada botol berbentuk daun hijau.', 31);

-- 4. INSERT Cewek perfumes (from perfumeDataCewek.ts)
INSERT INTO perfumes (name, brand, full_name, year, gender, category, concentration, notes, karakter, penggunaan, description, is_official, note, display_order) VALUES
('Scandalous', 'Victoria''s Secret', 'Victoria''s Secret Scandalous EDP', 2012, 'wanita', 'Floral Fruity Musk', 'EDP', '{"top": ["Bergamot", "Black Cherry", "Red Berry"], "middle": ["Jasmine", "Tuberose", "Peony"], "base": ["Musk", "Sandalwood", "Amber", "Vanilla"]}', 'Sensual, fruity-floral gelap, berani, feminin kuat', 'Malam hari, pesta, date night, acara sosial', 'Scandalous adalah parfum yang tidak meminta izin.', true, NULL, 32),
('Romantic Wish', 'Anne Möller', 'Anne Möller Romantic Wish EDT', 2006, 'wanita', 'Floral Fruity Powdery', 'EDT', '{"top": ["Mandarin Orange", "Raspberry", "Pink Grapefruit"], "middle": ["Peony", "Rose", "Violet"], "base": ["Musk", "Sandalwood", "Cedarwood", "White Amber"]}', 'Manis romantis, powdery feminine, dreamy', 'Siang hari, hangout, casual date, daily feminine', 'Romantic Wish adalah mimpi seorang romantis yang dituangkan ke dalam botol.', true, NULL, 33),
('Chloé EDP (Rose)', 'Chloé', 'Chloé Eau de Parfum', 2008, 'wanita', 'Floral Powdery', 'EDP', '{"top": ["Peony", "Pink Pepper", "Rose Bud"], "middle": ["Rose (Centifolia)", "Magnolia", "Lily of the Valley"], "base": ["Cedar", "Virginia Cedar", "Amber"]}', 'Elegan timeless, rose centered, sophisticated feminine', 'Acara formal, kantor feminin, everyday luxury', 'Chloé EDP adalah definisi dari ''understated luxury''.', true, 'Dikenal juga sebagai ''Chloé Rose'' di kalangan pengguna Indonesia.', 34),
('Cool Water Woman', 'Davidoff', 'Davidoff Cool Water Woman EDT', 1996, 'wanita', 'Floral Aquatic', 'EDT', '{"top": ["Pineapple", "Quince", "Black Currant", "Melon", "Waterlily"], "middle": ["Lotus Blossom", "Jasmine", "Rose"], "base": ["Musk", "Sandalwood", "Amber", "Cedarwood"]}', 'Segar aquatic feminin, bersih, summer vibes', 'Siang hari, musim panas, pantai, outdoor aktif', 'Cool Water Woman adalah saudara perempuan dari legenda aquatic.', true, NULL, 35),
('Candy Baby', 'Generic / Various', 'Candy Baby (Sweet Gourmand)', NULL, 'wanita', 'Gourmand Sweet Vanilla', 'EDP / Body Mist', '{"top": ["Cotton Candy", "Caramel", "Pink Sugar"], "middle": ["Vanilla Cream", "White Musk", "Peach"], "base": ["Sandalwood", "Amber", "Benzoin"]}', 'Manis ekstrem, girly, playful, candy-like', 'Casual, remaja, hangout, daily playful', 'Candy Baby adalah parfum yang tidak pernah berpura-pura menjadi sesuatu yang bukan dirinya.', false, '⚠️ ''Candy Baby'' adalah nama generik.', 36),
('Love Sarah', 'Yardley / Generic', 'Love Sarah (Floral Sweet)', NULL, 'wanita', 'Floral Sweet Powdery', 'EDT / EDP', '{"top": ["Pink Rose", "Freesia", "Bergamot"], "middle": ["Peony", "Lily", "Jasmine"], "base": ["White Musk", "Sandalwood", "Vanilla", "Cedar"]}', 'Lembut romantis, floral manis, soft powdery', 'Harian, casual feminine, daily comfort', 'Love Sarah memancarkan karakter yang sesuai namanya.', false, '⚠️ ''Love Sarah'' adalah nama yang digunakan berbagai brand lokal.', 37),
('Bombshell', 'Victoria''s Secret', 'Victoria''s Secret Bombshell EDP', 2010, 'wanita', 'Floral Fruity', 'EDP', '{"top": ["Purple Passion Fruit", "Shangri-La Peony", "Vanilla Orchid"], "middle": ["Jasmine Petals", "Brazilian Sandalwood", "White Amber"], "base": ["White Musk", "Sandalwood", "Vanilla"]}', 'Playful, cerah buah-buahan, confident feminine', 'Harian, hangout, daytime, casual dan festive', 'Bombshell adalah parfum yang paling ikonik dari Victoria''s Secret.', true, NULL, 38),
('Pink Chiffon', 'Victoria''s Secret', 'Victoria''s Secret Pink Chiffon Body Mist / EDP', 2015, 'wanita', 'Floral Fruity Powdery', 'Body Mist / EDT', '{"top": ["Mandarin Orange", "Watermelon", "Peach Blossom"], "middle": ["Jasmine", "Magnolia", "Lily"], "base": ["White Musk", "Sandalwood", "Soft Amber"]}', 'Ringan, powdery pink, innocent feminine, youthful', 'Siang hari, casual, daily, musim panas', 'Pink Chiffon adalah wujud dari warna pink dalam bentuk aroma.', true, NULL, 39),
('Black Star', 'Avril Lavigne', 'Avril Lavigne Black Star EDP', 2009, 'wanita', 'Floral Fruity Gourmand', 'EDP', '{"top": ["Black Cherry", "Red Berries", "Plum"], "middle": ["Gardenia", "Peony", "Night-blooming Jasmine"], "base": ["Vanilla", "Musk", "Dark Amber", "Patchouli"]}', 'Dark fruity-floral, rockstar feminine, edgy sweet', 'Malam hari, hangout malam, konser, casual edgy', 'Black Star adalah bukti bahwa Avril Lavigne tidak membuat parfum setengah-setengah.', true, NULL, 40),
('Roses Musk', 'Mancera', 'Mancera Roses Musk EDP', 2013, 'wanita', 'Floral Musk', 'EDP', '{"top": ["Rose", "Bergamot", "Peach"], "middle": ["Rose", "Peony", "Jasmine"], "base": ["White Musk", "Sandalwood", "Amber", "Musks"]}', 'Rose musk premium, elegan lembut, long-lasting', 'Daily luxury, acara formal, signature scent wanita', 'Mancera Roses Musk adalah mahakarya simplicity.', true, 'Dikenal sebagai ''Mancera Rose'' di kalangan pengguna.', 41),
('Very Sexy', 'Victoria''s Secret', 'Victoria''s Secret Very Sexy EDP', 2002, 'wanita', 'Oriental Floral', 'EDP', '{"top": ["Mandarin Orange", "Bergamot", "Pink Pepper"], "middle": ["Jasmine", "Orange Blossom", "Tuberose", "Ylang-ylang"], "base": ["Sandalwood", "Musk", "Amber", "Vanilla"]}', 'Sensual, seduktif, feminine powerful, signature VS', 'Malam hari, date night, acara glamor', 'Very Sexy tidak membuat klaim yang tidak bisa dipenuhi.', true, NULL, 42),
('Angel Heart', 'Cacharel', 'Cacharel Angel Heart EDT', 2007, 'wanita', 'Floral Fruity Sweet', 'EDT', '{"top": ["Lychee", "Tangerine", "Raspberry", "Melon"], "middle": ["Lily of the Valley", "Rose", "Magnolia", "Camellia"], "base": ["Musk", "Amber", "Sandalwood", "Cedar"]}', 'Innocent sweet, floral buah-buahan, girly romantic', 'Siang hari, casual, daily youthful, hangout', 'Angel Heart dari Cacharel adalah ekspresi dari cinta pertama.', true, NULL, 43),
('Vanilla Ice', 'Generic / Various', 'Vanilla Ice (Sweet Vanilla Musk)', NULL, 'wanita', 'Gourmand Sweet Oriental', 'EDP / Body Mist', '{"top": ["Vanilla Cream", "Coconut Milk", "Caramel"], "middle": ["Benzoin", "Tonka Bean", "White Musk"], "base": ["Sandalwood", "Amber", "Warm Musks"]}', 'Creamy vanilla hangat, comfort scent, cozy feminine', 'Malam hari, musim hujan, me-time, comfort daily', 'Vanilla Ice adalah pelukan dalam bentuk aroma.', false, '⚠️ ''Vanilla Ice'' adalah nama yang digunakan banyak brand lokal.', 44),
('Omnia Crystalline', 'Bvlgari', 'Bvlgari Omnia Crystalline EDT', 2005, 'wanita', 'Floral Woody', 'EDT', '{"top": ["Nashi Pear", "Lotus Flower", "Bamboo"], "middle": ["White Tea", "Balsa Wood", "Wheat"], "base": ["White Musk", "Sandalwood"]}', 'Crystal clean, ultra-segar, transparent modern', 'Kantor, daily clean, ruang tertutup, semua waktu', 'Omnia Crystalline adalah parfum yang paling ''transparan'' yang pernah ada.', true, 'Dikenal sebagai ''Bulgari Crystal'' di kalangan pengguna Indonesia.', 45),
('Nagita Slavina Signature', 'Lokal / Inspired', 'Parfum Nagita Slavina (Inspired/Clone)', NULL, 'wanita', 'Floral Oriental Sweet', 'EDP', '{"top": ["Bergamot", "Peach", "Pink Pepper"], "middle": ["Rose", "Jasmine", "Peony"], "base": ["Vanilla", "Sandalwood", "White Musk", "Amber"]}', 'Feminine premium, warm floral, glamorous', 'Acara penting, evening, signature statement', 'Representasikan estetika ''celebrity fragrance''.', false, '⚠️ Tidak ada parfum resmi dengan brand ''Nagita Slavina''.', 46),
('Soft', 'Al-Rehab', 'Al-Rehab Soft EDP', 2010, 'unisex', 'Floral Musk Soft', 'EDP (Concentrated Perfume Oil)', '{"top": ["Rose", "Jasmine", "Citrus"], "middle": ["White Musk", "Floral Bouquet", "Lily"], "base": ["Sandalwood", "Amber", "Warm Musk"]}', 'Sangat lembut, clean musk, skin-like, versatile', 'Harian, semua waktu, kantor, casual, halal-friendly', 'Al-Rehab Soft dari Arab Saudi adalah fenomena tersendiri.', true, 'Al-Rehab adalah brand parfum Arab Saudi yang menggunakan concentrated perfume oil.', 47),
('Love Sarah II', 'Yardley / Generic', 'Love Sarah (Varian / Variant)', NULL, 'wanita', 'Floral Powdery Sweet', 'EDT', '{"top": ["Strawberry", "Pink Rose", "Bergamot"], "middle": ["Jasmine", "Gardenia", "Violet"], "base": ["Sandalwood", "White Musk", "Vanilla", "Powder"]}', 'Powdery sweet, classic feminine, nostalgic', 'Harian feminine, casual, everyday comfort', 'Varian kedua dari Love Sarah menawarkan interpretasi yang sedikit berbeda.', false, '⚠️ Love Sarah muncul dua kali dalam daftar.', 48),
('Olla Ramlan Signature', 'Lokal / Inspired', 'Parfum Olla Ramlan (Inspired/Clone)', NULL, 'wanita', 'Floral Woody Musk', 'EDP', '{"top": ["Bergamot", "Mandarin Orange", "Freesia"], "middle": ["Rose", "Jasmine", "Lily of the Valley"], "base": ["Cedarwood", "White Musk", "Sandalwood", "Vanilla"]}', 'Elegant modern, feminine sophisticated, natural clean', 'Daily wear, kantor, casual elegant', 'Mencerminkan estetika feminin yang elegant dan modern.', false, '⚠️ Tidak ada parfum resmi dengan brand ''Olla Ramlan''.', 49),
('Orchid', 'Zara', 'Zara Orchid EDP', 2018, 'wanita', 'Floral Oriental', 'EDP', '{"top": ["Raspberry", "Bergamot", "Magnolia"], "middle": ["Orchid", "Jasmine", "Rose"], "base": ["Patchouli", "Amber", "Sandalwood", "Vanilla"]}', 'Elegan terjangkau, Oriental floral, ''expensive smell''', 'Daily luxury, malam, acara semi-formal', 'Salah satu pencapaian terbesar dalam kategori ''luxury on a budget''.', true, NULL, 50),
('Terre d''Hermès', 'Hermès', 'Hermès Terre d''Hermès (versi unisex/femme)', 2006, 'unisex', 'Woody Citrus Mineral', 'EDT / EDP', '{"top": ["Grapefruit", "Orange", "Ginger"], "middle": ["Pepper", "Pelargonium", "Patchouli"], "base": ["Vetiver", "Benzoin", "Cedar", "Flint"]}', 'Earthy woody mineral, sophisticated unisex, signature house', 'Acara formal, daily premium, signature unisex', 'Terre d''Hermès adalah parfum yang merayakan bumi.', true, 'Originally masculine, namun karakter earthy-nya menjadikannya favorit unisex.', 51),
('Twilly d''Hermès', 'Hermès', 'Hermès Twilly d''Hermès EDP', 2017, 'wanita', 'Floral Woody', 'EDP', '{"top": ["Ginger", "Tuberose"], "middle": ["Tuberose", "White Floral"], "base": ["Sandalwood", "Musk"]}', 'Playful mewah, tuberose modern, Hermès femininity', 'Acara spesial, daily luxury, signature feminin premium', 'Parfum yang merayakan roh muda yang bebas.', true, NULL, 52),
('Incanto Shine', 'Salvatore Ferragamo', 'Salvatore Ferragamo Incanto Shine EDT', 2007, 'wanita', 'Floral Fruity Aquatic', 'EDT', '{"top": ["Pineapple", "Pink Grapefruit", "Nectarine"], "middle": ["Peony", "Waterlily", "Lily of the Valley"], "base": ["White Musk", "Sandalwood", "Cedar"]}', 'Segar tropis, aquatic fruity, bersih cerah, musim panas', 'Siang hari, musim panas, pantai, casual fresh', 'Incanto Shine adalah botol berisi sinar matahari tropis.', true, NULL, 53),
('Selena Gomez EDP', 'Selena Gomez', 'Selena Gomez EDP', 2013, 'wanita', 'Floral Fruity Oriental', 'EDP', '{"top": ["Water Hyacinth", "Mandarin Orange", "Cassia"], "middle": ["Orchid", "Peony", "Jasmine"], "base": ["Sandalwood", "Amber", "Vanilla", "Musk"]}', 'Youthful floral, accessible luxury, warm feminine', 'Harian, casual, hangout, daytime', 'Menangkap esensi dari wanita muda yang sedang dalam proses menemukan dirinya.', true, NULL, 54),
('Bubble Gum', 'Generic / Various', 'Bubble Gum (Sweet Fruity)', NULL, 'wanita', 'Gourmand Sweet Fruity', 'Body Mist / EDT', '{"top": ["Bubble Gum", "Strawberry", "Watermelon"], "middle": ["Vanilla Cream", "White Flowers", "Peach"], "base": ["Sweet Musk", "Caramel", "Benzoin"]}', 'Manis ekstrem, playful childlike, casual fun', 'Casual sangat, remaja, hangout, konser pop', 'Bubble Gum adalah parfum yang paling tidak mengambil dirinya terlalu serius.', false, '⚠️ ''Bubble Gum'' adalah nama yang digunakan banyak brand.', 55),
('Zwitsal Baby', 'Zwitsal', 'Zwitsal Baby Cologne', 1900, 'unisex', 'Powdery Fresh Clean', 'Cologne / Light EDT', '{"top": ["Citrus", "Light Aldehydes", "Talcum"], "middle": ["White Musk", "Powder", "Light Floral"], "base": ["Baby Powder", "Sandalwood", "Soft Amber"]}', 'Baby powder clean, nostalgic, universally comforting', 'Casual, daily, semua situasi ringan, comfort scent', 'Salah satu aroma paling universally recognized di Indonesia.', true, NULL, 56),
('Lux', 'Lux / Generic', 'Lux Fragrance (Body Wash Inspired / EDT)', NULL, 'wanita', 'Floral Clean Fresh', 'EDT / Body Mist', '{"top": ["Violet", "Rose", "White Musk"], "middle": ["Jasmine", "Lily", "Soft Floral"], "base": ["White Musk", "Clean Musk", "Sandalwood"]}', 'Clean floral, soapy fresh, feminine bersih', 'Harian, casual, semua waktu', 'Terinspirasi dari karakter aroma brand sabun mandi Lux.', false, '⚠️ ''Lux'' sebagai parfum standalone tidak memiliki identitas global resmi.', 57),
('Still', 'Jennifer Lopez', 'Jennifer Lopez Still EDP', 2003, 'wanita', 'Floral Musky Soft', 'EDP', '{"top": ["Bergamot", "Neroli", "Green Leaves"], "middle": ["Lily of the Valley", "Jasmine", "White Magnolia"], "base": ["White Musk", "Sandalwood", "Amber", "Vetiver"]}', 'Soft elegant, clean musky, sophisticated tenang', 'Kantor, daily feminine, ruang tertutup, versatile', 'Still adalah parfum JLo yang paling terkendali dan paling sophisticated.', true, NULL, 58),
('Paris Hilton', 'Paris Hilton', 'Paris Hilton EDP', 2004, 'wanita', 'Floral Fruity', 'EDP', '{"top": ["Peach", "Apple", "Frozen Lychee", "Mandarin Orange", "Quince"], "middle": ["Gardenia", "Ylang-Ylang", "Mimosa", "Lily of the Valley", "Jasmine"], "base": ["Sandalwood", "Musk", "Amber", "Oakmoss", "Vetiver", "Coumarin"]}', 'Fruity floral feminine, glamorous, ikon 2000-an', 'Siang hingga sore, casual glamor, hangout', 'Kapsul waktu yang sempurna dari awal 2000-an.', true, NULL, 59),
('Heiress', 'Paris Hilton', 'Paris Hilton Heiress EDT', 2006, 'wanita', 'Floral Fruity Powdery', 'EDT', '{"top": ["Tangerine", "Watermelon", "Honeysuckle"], "middle": ["Tuberose", "Lily of the Valley", "Gardenia", "Jasmine"], "base": ["Musk", "Sandalwood", "Amber", "Cedarwood"]}', 'Girly floral, powdery princess, playful feminine', 'Siang hari, casual, hangout, summer', 'Versi Paris Hilton yang lebih muda dan lebih playful.', true, NULL, 60),
('Wonderstruck', 'Taylor Swift', 'Taylor Swift Wonderstruck EDP', 2011, 'wanita', 'Floral Fruity Warm', 'EDP', '{"top": ["Raspberry", "Apple Blossom", "Freesia"], "middle": ["Peony", "Jasmine", "Magnolia"], "base": ["Sandalwood", "Amber", "Vanilla", "Musk"]}', 'Fairytale feminine, warm floral, dreamy romantic', 'Harian, hangout, casual romantic, everyday feminine', 'Merangkum dunia Taylor Swift dengan sangat akurat.', true, NULL, 61),
('English Pear & Freesia', 'Jo Malone London', 'Jo Malone English Pear & Freesia Cologne', 2012, 'unisex', 'Floral Fruity', 'Cologne (Jo Malone signature format)', '{"top": ["Pear", "Melon", "Galbanum"], "middle": ["Freesia", "Rose", "Rhubarb"], "base": ["Amber", "Patchouli", "Benzoin", "Woody Notes"]}', 'Autumnal British elegance, clean pear, sophisticated', 'Sepanjang hari, formal dan casual, signature Jo Malone', 'Capture musim gugur Inggris dengan cara yang sangat poetic.', true, NULL, 62),
('Aqua Kiss', 'Victoria''s Secret', 'Victoria''s Secret Aqua Kiss Refreshing Body Mist', 2014, 'wanita', 'Aquatic Floral Fresh', 'Body Mist / Light EDT', '{"top": ["Sea Notes", "Bergamot", "Watery Citrus"], "middle": ["Water Lily", "Jasmine", "Aqueous Floral"], "base": ["White Musk", "Driftwood", "Clean Amber"]}', 'Ultra segar aquatic, bersih ringan, after-beach', 'Siang hari, musim panas, pantai, casual fresh', 'Aqua Kiss lahir dari philosophy ''kesegaran yang tidak berkompromi''.', true, NULL, 63),
('Miss Dior Blooming Bouquet', 'Christian Dior', 'Miss Dior Blooming Bouquet EDT', 2014, 'wanita', 'Floral Fruity', 'EDT', '{"top": ["Pear", "Raspberry", "Pink Grapefruit"], "middle": ["Peony", "White Rose", "Jasmine Sambac"], "base": ["White Musk", "Sandalwood", "Pink Peppercorn"]}', 'Spring garden feminine, bouquet segar, accessible Dior', 'Siang hari, hangout, daily fresh, spring-summer', 'Paling accessible dan paling carefree dari keluarga Miss Dior.', true, NULL, 64),
('Flora by Gucci', 'Gucci', 'Gucci Flora Gorgeous Gardenia EDP', 2009, 'wanita', 'Floral Fruity', 'EDP', '{"top": ["Red Berries", "Brown Sugar"], "middle": ["Gardenia", "Frangipani"], "base": ["Patchouli", "Brown Sugar", "Cashmeran"]}', 'Lush tropical floral, feminine sophisticated, iconic Gucci', 'Malam hingga siang, acara spesial, signature Gucci', 'Mahkota dari lini Flora Gucci.', true, NULL, 65),
('Dreams', 'Anna Sui', 'Anna Sui Dreams EDT', 2014, 'wanita', 'Floral Fruity', 'EDT', '{"top": ["Blackcurrant", "Bergamot", "Mandarin Orange"], "middle": ["Jasmine", "Rose", "Violet"], "base": ["Musk", "Cedarwood", "Sandalwood"]}', 'Dreamy feminine, fairytale floral, playful-elegant', 'Siang hari, casual, daily youthful, hangout', 'Parfum yang benar-benar tentang mimpi dalam semua maknanya.', true, NULL, 66);

-- 5. INDEXES for better search performance
CREATE INDEX IF NOT EXISTS idx_perfumes_name ON perfumes(name);
CREATE INDEX IF NOT EXISTS idx_perfumes_gender ON perfumes(gender);

-- 6. ENABLE Row Level Security
ALTER TABLE perfumes ENABLE ROW LEVEL SECURITY;

-- 7. CREATE POLICY to allow public read access
-- 'USING (true)' allows everyone (including anonymous users) to read the data.
CREATE POLICY "nuxar_perfumes_public_read" 
ON public.perfumes 
FOR SELECT 
TO public 
USING (true);
